server:
  port: 8080

security:
  enabled: ${SECURITY_ENABLED}

spring:
  banner:
    location: classpath:banner.txt
  application:
    name: dq-mail
  messages:
    basename: i18n.messages
  freemarker:
    cache: false
    template-loader-path: ${MAIL_TEMPLATE_LOADER_TYPE:file}:${MAIL_TEMPLATE_PATH}
  mail:
    default-encoding: ${MAIL_ENCODING}
    host: ${MAIL_HOST}
    protocol: ${MAIL_PROTOCOL}
    port: ${MAIL_PORT}
    username: ${MAIL_LOGIN}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
    test-connection: false
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  level:
    root: ${LOGGING_ROOT_LEVEL}
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  health:
    defaults:
      enabled: true