server:
  port: 8080

security:
  enabled: false

spring:
  freemarker:
    cache: false
    template-loader-path: file:/home/alexey/templates
  mail:
    default-encoding: UTF-8
    host: smtp.mail.ru
    protocol: smtp
    port: 587
    username: iworking.ru@mail.ru
    password: aZIjJbw75sCWHrEjwAbX
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
    test-connection: false
logging:
  level:
    root: INFO
