FROM registry.diasoft.ru:5000/diasoft-parent-jdk8:latest
VOLUME /tmp

#В директории FTSysConfigManager должны быть размещены файлы, требующиеся для продукта "Инсталлятор". В частности, файл properties.properties.
ADD docker/properties.properties /FTSysConfigManager/properties.properties

COPY ./service/target/dq-mail-service-*.jar app.jar

COPY ./templates /share/pv/html-mail-templates

ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar","/app.jar"]
